spring.application.name=ExpenseTrackerRestApi

server.port=${PORT:8080}


# ===============================
# DATABASE
# ===============================



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration=1800000

# ===============================
# SECURITY LOGGING
# ===============================

logging.level.org.springframework.security=INFO



#PRIVIOUS CODE ---------

#spring.application.name=ExpenseTrackerRestApi

#spring.datasource.url=jdbc:mysql://localhost:3306/Your_Database_Name
#spring.datasource.username=Your_Username
#spring.datasource.password=Your_Password

#spring.jpa.hibernate.ddl.auto=update
#spring.jpa.show-sql=true
#sping.jpa.properties.hibernate.formate_sql=true

#jwt.secret=MyVeryStrongSecretKeyForExpenseTrackerProject123456789
#jwt.expiration=1800000

#logging.level.org.springframework.security=TRACE


