spring.application.name=ExpenseTrackerRestApi

spring.datasource.url=jdbc:mysql://localhost:3306/Your_Database_Name
spring.datasource.username=Your_Username
spring.datasource.password=Your_Password

spring.jpa.hibernate.ddl.auto=update
spring.jpa.show-sql=true
sping.jpa.properties.hibernate.formate_sql=true

jwt.secret=MyVeryStrongSecretKeyForExpenseTrackerProject123456789
jwt.expiration=1800000

logging.level.org.springframework.security=TRACE